// file autogenerated by platonicSTLgen
// author: thanasi athanassiadis (thanasi@uchicago.edu)
// script dated: august 25, 2012

include <../platonic.scad>

// units are mm

rad = 1.761182;

// poly = sphere(rad);

for(i = [ [0.000000,0.000000,0.000000] ])
{
    translate(i)
    sphere(r=rad, $fn=50);
}

module display_polyhedron(poly) 
{
polyhedron(points = poly[0], triangles = poly[1]);
}

